
async_constant <- async(async_constant)
async_detect   <- async(async_detect)
async_every    <- async(async_every)
async_filter   <- async(async_filter)
async_map      <- async(async_map)
async_retry    <- async(async_retry)
async_some     <- async(async_some)
async_timeout  <- async(async_timeout)
async_until    <- async(async_until)
async_whilst   <- async(async_whilst)
delay          <- async(delay)
http_get       <- async(http_get)
http_head      <- async(http_head)
